import { BadgeCheck, Gift, Plane, ShoppingBag, UserRoundCheck, Users } from "lucide-react";
import { summarizeCustomerJourney } from "@/lib/commerce-insights";
import "./customers.css";

export default function CustomersPage() {
  const summary = summarizeCustomerJourney([]);
  return <main className="customersPage"><section className="customersTitle"><p>CUSTOMER JOURNEY</p><h1>Product shoppers.<br/><span>Future travelers.</span></h1><div>Track each verified buyer from affiliate order through reward delivery, vacation-planning interest, qualification, and booking.</div></section><section className="customerMetrics"><Metric icon={<ShoppingBag/>} label="Verified shoppers" value={summary.shoppers}/><Metric icon={<Gift/>} label="Rewards issued" value={summary.rewardsIssued}/><Metric icon={<Plane/>} label="Planning interest" value={summary.planningInterest}/><Metric icon={<UserRoundCheck/>} label="Qualified travel leads" value={summary.qualifiedTravelLeads}/><Metric icon={<BadgeCheck/>} label="Booked clients" value={summary.bookedClients}/></section><section className="customerPipeline"><Stage icon={<ShoppingBag/>} title="Purchased" detail="Verified affiliate orders enter the journey."/><Stage icon={<Gift/>} title="Reward issued" detail="Eligible shoppers receive one planning reward."/><Stage icon={<Plane/>} title="Planning interest" detail="The shopper requests help planning a vacation."/><Stage icon={<UserRoundCheck/>} title="Qualified lead" detail="Needs, timing, and travel intent are confirmed."/><Stage icon={<BadgeCheck/>} title="Booked client" detail="The shopper becomes a travel customer."/></section><section className="customerEmpty"><Users/><h2>No verified shoppers yet</h2><p>This workspace will populate only after founder authentication, affiliate order verification, and customer-consent controls are connected.</p><span>CUSTOMER DATA REMAINS PROTECTED</span></section></main>;
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <article><div>{icon}</div><span>{label}</span><strong>{value}</strong></article>; }
function Stage({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <article><div>{icon}</div><h2>{title}</h2><p>{detail}</p></article>; }
