import Link from "next/link";
import { ArrowRight, Bot, Boxes, Gift, Radio, ShieldCheck, Sparkles, Users } from "lucide-react";
import { channelPolicies, travelProductCatalog } from "@/lib/travel-commerce";
import { getPlanningRewardPublicConfig } from "@/lib/planning-rewards";
import "./dashboard.css";

export default function DashboardPage() {
  const reward = getPlanningRewardPublicConfig();
  const autonomousChannels = Object.values(channelPolicies).filter((channel) => channel.mode === "autonomous").length;
  return <main className="dashboardPage">
    <section className="dashboardWelcome"><div><p>FOUNDER COMMAND CENTER</p><h1>One platform.<br/><span>One revenue journey.</span></h1><div>Operate the avatar studio, select travel products, govern affiliate channels, and convert verified shoppers into vacation-planning clients.</div></div><Link href="/" className="dashboardPrimary">Open Live Studio <ArrowRight/></Link></section>
    <section className="dashboardMetrics"><Metric icon={<Boxes/>} label="Travel products" value={String(travelProductCatalog.length)} detail="Starter intelligence catalog"/><Metric icon={<Radio/>} label="Autonomous channels" value={String(autonomousChannels)} detail="Owned network eligible"/><Metric icon={<Gift/>} label="Planning reward" value={`${reward.discountValue}%`} detail={`Up to $${reward.maximumDiscountCents / 100}`}/><Metric icon={<Users/>} label="Customer journey" value="CONNECTED" detail="Purchase → planning lead"/></section>
    <section className="dashboardWorkspaceGrid"><Workspace href="/" icon={<Radio/>} eyebrow="CREATE" title="Live Studio" description="Choose a product, AI host, script, layout, voice, and broadcast destination." action="Build a stream"/><Workspace href="/commerce" icon={<Bot/>} eyebrow="AUTOMATE" title="Commerce Intelligence" description="Rank travel products, apply channel rules, and generate an adaptive sales cycle." action="Plan the next pitch"/><Workspace href="/rewards" icon={<Gift/>} eyebrow="CONVERT" title="Vacation Rewards" description="Turn qualifying product buyers into professional vacation-planning prospects." action="Manage the offer"/></section>
    <section className="journeyPanel"><div className="journeyHeading"><div><p>CONNECTED CUSTOMER JOURNEY</p><h2>From product problem to vacation client</h2></div><ShieldCheck/></div><div className="journeyRail"><Journey number="01" title="Travel need" detail="A shopper discovers a relevant travel essential."/><Journey number="02" title="Avatar pitch" detail="FacelessLive demonstrates verified benefits."/><Journey number="03" title="Affiliate purchase" detail="The authorized channel records the order."/><Journey number="04" title="Reward issued" detail="A qualifying order unlocks planning savings."/><Journey number="05" title="Travel client" detail="The shopper requests professional trip planning."/></div><div className="dashboardNotice"><Sparkles/><span>The public shopper page remains separate from founder controls while sharing the same FacelessLive brand and reward configuration.</span><Link href="/vacation-planning">Preview shopper page</Link></div></section>
  </main>;
}
function Metric({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string; detail: string }) { return <article className="dashboardMetric"><div>{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }
function Workspace({ href, icon, eyebrow, title, description, action }: { href: string; icon: React.ReactNode; eyebrow: string; title: string; description: string; action: string }) { return <Link className="workspaceCard" href={href}><div className="workspaceIcon">{icon}</div><span>{eyebrow}</span><h2>{title}</h2><p>{description}</p><strong>{action} <ArrowRight size={17}/></strong></Link>; }
function Journey({ number, title, detail }: { number: string; title: string; detail: string }) { return <article><b>{number}</b><h3>{title}</h3><p>{detail}</p></article>; }
